name: release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        run: |
          yarn
          yarn release
